### ISSUE TITLE
Exception when no dumps file

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLExplorer#53]
[ERROR] Returning error [Errno 2] No such file or directory: 'dumps/uri2rank_dump'
 Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/SBOLExplorer/flask/explorer.py", line 120, in sparql_search_endpoint
    response = jsonify(search.search(sparql_query, utils.get_uri2rank(), utils.get_clusters()))
  File "/SBOLExplorer/flask/utils.py", line 114, in get_uri2rank
    uri2rank = deserialize(uri2rank_filename)
  File "/SBOLExplorer/flask/utils.py", line 126, in deserialize
    f = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'dumps/uri2rank_dump'

**Comment by yu-eric** [comment]
@cjmyers See #60

**Comment by yu-eric** [comment]
Should be fixed in the PR.
